// src/components/Calendar.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import encryptTokenForHeader from '@/utils/crypto';

const CMB_BASE = import.meta.env.VITE_CMB_BASE || 'https://cmb2.duckdns.org';

function Calendar() {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(false);
  const [showEventModal, setShowEventModal] = useState(false);
  const [expandedEventId, setExpandedEventId] = useState(null);
  const [showDatePicker, setShowDatePicker] = useState(false);

  const monthYear = new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric' }).format(currentDate);
  const SSO_API_TOKEN = import.meta.env.VITE_SSO_GENERATE_TOKEN || import.meta.env.VITE_CMB_API_TOKEN || "";

  // Fetch calendar events from CMB API
  const fetchEvents = async (date) => {
    setLoading(true);
    try {
      // Format period as YYYY-MM
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const period = `${year}-${month}`;
      
      const url = `${CMB_BASE}/calendar/fetch?period=${period}`;
      const apIToken = await encryptTokenForHeader(SSO_API_TOKEN, { salt: SSO_API_TOKEN });
      const response = await axios.get(url, {
        headers: {
          'Accept': 'application/json',
          'X-Api-Token': apIToken
        }
      });
      
      if (response.data && response.data.events) {
        // Transform Google Calendar API data to events format
        const calendarEvents = response.data.events.map(event => {
          const isNationalHoliday = event.organizer?.email === 'id.indonesian#holiday@group.v.calendar.google.com';
          const startDate = event.start?.date || event.start_local || event.start_raw;
          
          // Parse date properly - ensure it's treated as local date
          const [year, month, day] = startDate.split('-').map(Number);
          const eventDate = new Date(year, month - 1, day);
          
          return {
            id: event.id,
            title: event.summary || 'Event',
            date: eventDate,
            type: isNationalHoliday ? 'holiday' : 'event',
            description: event.description || event.summary,
            isNationalHoliday: isNationalHoliday,
            location: event.location,
            htmlLink: event.htmlLink,
            creator: event.creator?.displayName,
            start: startDate,
            end: event.end?.date || event.end_local || event.end_raw,
            rawEvent: event
          };
        });
        setEvents(calendarEvents);
      }
    } catch (error) {
      console.error('Error fetching events:', error);
      // Set empty array on error to prevent crashes
      setEvents([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchEvents(currentDate);
  }, [currentDate.getMonth(), currentDate.getFullYear()]);

  const prevMonth = () => {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1));
  };

  const nextMonth = () => {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1));
  };

  const goToToday = () => {
    const today = new Date();
    setCurrentDate(today);
    setSelectedDate(today);
  };

  const refresh = () => {
    fetchEvents(currentDate);
  };

  const getDaysInMonth = (date) => {
    const year = date.getFullYear();
    const month = date.getMonth();
    const firstDay = new Date(year, month, 1);
    const lastDay = new Date(year, month + 1, 0);
    const daysInMonth = lastDay.getDate();
    const startingDayOfWeek = firstDay.getDay();
    
    const days = [];
    // Add empty cells for days before month starts
    for (let i = 0; i < startingDayOfWeek; i++) {
      days.push(null);
    }
    // Add days of month
    for (let i = 1; i <= daysInMonth; i++) {
      days.push(new Date(year, month, i));
    }
    return days;
  };

  const isToday = (date) => {
    if (!date) return false;
    const today = new Date();
    return date.getDate() === today.getDate() &&
           date.getMonth() === today.getMonth() &&
           date.getFullYear() === today.getFullYear();
  };

  const isSelected = (date) => {
    if (!date) return false;
    return date.getDate() === selectedDate.getDate() &&
           date.getMonth() === selectedDate.getMonth() &&
           date.getFullYear() === selectedDate.getFullYear();
  };

  // Check if date has events
  const hasEvent = (date) => {
    if (!date) return false;
    return events.some(event => 
      event.date.getDate() === date.getDate() &&
      event.date.getMonth() === date.getMonth() &&
      event.date.getFullYear() === date.getFullYear()
    );
  };

  // Check if date is a holiday
  const isHoliday = (date) => {
    if (!date) return false;
    return events.some(event => 
      event.isNationalHoliday &&
      event.date.getDate() === date.getDate() &&
      event.date.getMonth() === date.getMonth() &&
      event.date.getFullYear() === date.getFullYear()
    );
  };

  // Check if date is Sunday
  const isSunday = (date) => {
    if (!date) return false;
    return date.getDay() === 0;
  };

  // Get events for a specific date
  const getEventsForDate = (date) => {
    if (!date) return [];
    return events.filter(event => 
      event.date.getDate() === date.getDate() &&
      event.date.getMonth() === date.getMonth() &&
      event.date.getFullYear() === date.getFullYear()
    );
  };

  // Handle date click
  const handleDateClick = (date) => {
    if (!date) return;
    setSelectedDate(date);
    const dateEvents = getEventsForDate(date);
    if (dateEvents.length > 0) {
      setExpandedEventId(null); // Reset expanded event
      setShowEventModal(true);
    }
  };

  const toggleEventDetail = (eventId) => {
    setExpandedEventId(expandedEventId === eventId ? null : eventId);
  };

  const handleMonthChange = (e) => {
    const month = parseInt(e.target.value);
    setCurrentDate(new Date(currentDate.getFullYear(), month, 1));
  };

  const handleYearChange = (e) => {
    const year = parseInt(e.target.value);
    setCurrentDate(new Date(year, currentDate.getMonth(), 1));
  };

  const selectedDateEvents = getEventsForDate(selectedDate);
  const days = getDaysInMonth(currentDate);
  const weekDays = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];

  return (
    <div>
      {loading && (
        <div className="flex justify-center items-center py-4">
          <svg className="animate-spin h-5 w-5 text-teal-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
          </svg>
        </div>
      )}
      
      <div className="p-4">
        <div className="mb-3">
          <div className="flex items-center justify-between mb-2">
            <button
              onClick={() => setShowDatePicker(!showDatePicker)}
              className="text-sm font-medium text-gray-900 dark:text-white hover:text-teal-600 dark:hover:text-teal-400 transition flex items-center gap-1"
            >
              {monthYear}
              <svg xmlns="http://www.w3.org/2000/svg" className={`h-4 w-4 transition-transform ${showDatePicker ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </button>
            <div className="flex items-center gap-2">
              <button
                onClick={prevMonth}
                aria-label="Bulan sebelumnya"
                className="inline-flex items-center justify-center h-8 w-8 rounded bg-white dark:bg-gray-700 border dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:shadow hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors duration-150"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="none" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4l-6 6 6 6" />
                </svg>
              </button>
              <button
                onClick={goToToday}
                className="px-2 py-1 rounded bg-teal-600 dark:bg-teal-700 text-white text-sm hover:brightness-95"
              >
                Hari ini
              </button>
              <button
                onClick={nextMonth}
                aria-label="Bulan berikutnya"
                className="inline-flex items-center justify-center h-8 w-8 rounded bg-white dark:bg-gray-700 border dark:border-gray-600 text-gray-700 dark:text-gray-300 hover:shadow hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors duration-150"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="none" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 4l6 6-6 6" />
                </svg>
              </button>
              <button
                onClick={refresh}
                title="Segarkan"
                className="ml-2 inline-flex items-center gap-2 px-2 py-2 rounded bg-white dark:bg-gray-700 border dark:border-gray-600 text-sm hover:shadow group transition-colors duration-150 hover:bg-gray-50 dark:hover:bg-gray-600 active:scale-95"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 transform transition-transform duration-200 ease-in-out group-hover:rotate-90 text-gray-700 dark:text-gray-300" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 12a9 9 0 11-9-9m0 0v4m0-4h4" />
                </svg>
              </button>
            </div>
          </div>

          {/* Date Picker */}
          {showDatePicker && (
            <div className="flex gap-2 mb-3 p-3 bg-gray-50 dark:bg-gray-700/50 rounded-lg border border-gray-200 dark:border-gray-600">
              <div className="flex-1">
                <label className="block text-xs text-gray-600 dark:text-gray-400 mb-1">Bulan</label>
                <select
                  value={currentDate.getMonth()}
                  onChange={handleMonthChange}
                  className="w-full px-2 py-1.5 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-teal-500 focus:border-teal-500"
                >
                  <option value={0}>Januari</option>
                  <option value={1}>Februari</option>
                  <option value={2}>Maret</option>
                  <option value={3}>April</option>
                  <option value={4}>Mei</option>
                  <option value={5}>Juni</option>
                  <option value={6}>Juli</option>
                  <option value={7}>Agustus</option>
                  <option value={8}>September</option>
                  <option value={9}>Oktober</option>
                  <option value={10}>November</option>
                  <option value={11}>Desember</option>
                </select>
              </div>
              <div className="flex-1">
                <label className="block text-xs text-gray-600 dark:text-gray-400 mb-1">Tahun</label>
                <select
                  value={currentDate.getFullYear()}
                  onChange={handleYearChange}
                  className="w-full px-2 py-1.5 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:ring-2 focus:ring-teal-500 focus:border-teal-500"
                >
                  {Array.from({ length: 10 }, (_, i) => new Date().getFullYear() - 5 + i).map(year => (
                    <option key={year} value={year}>{year}</option>
                  ))}
                </select>
              </div>
            </div>
          )}
        </div>

        {/* Calendar grid */}
        <div className="grid grid-cols-7 gap-1">
          {/* Week day headers */}
          {weekDays.map((day) => (
            <div key={day} className="text-center text-xs font-medium text-gray-500 dark:text-gray-400 py-2">
              {day}
            </div>
          ))}
          {/* Days */}
          {days.map((date, index) => {
            const hasEvents = hasEvent(date);
            const dateIsHoliday = isHoliday(date);
            const dateIsSunday = isSunday(date);
            const isRedDate = dateIsHoliday || dateIsSunday;
            
            return (
              <button
                key={index}
                onClick={() => handleDateClick(date)}
                disabled={!date}
                className={`
                  relative aspect-square text-sm rounded-lg transition-colors flex flex-col items-center justify-center
                  ${!date ? 'invisible' : ''}
                  ${isToday(date) ? 'bg-teal-600 dark:bg-teal-700 text-white font-semibold' : ''}
                  ${isSelected(date) && !isToday(date) ? 'bg-teal-100 dark:bg-teal-900/50 text-teal-900 dark:text-teal-100' : ''}
                  ${!isToday(date) && !isSelected(date) && !isRedDate ? 'text-gray-900 dark:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-700' : ''}
                  ${!isToday(date) && !isSelected(date) && isRedDate ? 'text-rose-600 dark:text-rose-400 font-semibold hover:bg-rose-50 dark:hover:bg-rose-900/20' : ''}
                  ${hasEvents && !isToday(date) ? 'ring-1 ring-rose-400 dark:ring-rose-500' : ''}
                `}
              >
                <span>{date && date.getDate()}</span>
                {isToday(date) && (
                  <span className="text-[9px] mt-0.5 opacity-90">Hari ini</span>
                )}
                {hasEvents && !isToday(date) && (
                  <span className="absolute bottom-1 w-1 h-1 rounded-full bg-rose-500 dark:bg-rose-400"></span>
                )}
              </button>
            );
          })}
        </div>

        {/* Event list for selected date */}
        {selectedDateEvents.length > 0 && (
          <div className="mt-4 border-t dark:border-gray-700 pt-4">
            <h5 className="text-xs font-semibold text-gray-700 dark:text-gray-300 mb-2">
              {new Intl.DateTimeFormat('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(selectedDate)}
            </h5>
            <div className="space-y-2">
              {selectedDateEvents.map((event) => (
                <div key={event.id} className="flex items-start gap-2 p-2 bg-rose-50 dark:bg-rose-900/20 rounded-lg border border-rose-100 dark:border-rose-800">
                  <div className="flex-shrink-0 mt-0.5">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-rose-600 dark:text-rose-400" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-gray-900 dark:text-gray-100">{event.title}</p>
                    {event.description && event.description !== event.title && (
                      <p className="text-xs text-gray-600 dark:text-gray-400">{event.description}</p>
                    )}
                    {event.isNationalHoliday && (
                      <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-rose-100 dark:bg-rose-900/30 text-rose-800 dark:text-rose-300 mt-1">
                        Hari Libur Nasional
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Event Modal */}
      {showEventModal && selectedDateEvents.length > 0 && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={() => setShowEventModal(false)}>
          <div className="absolute inset-0 bg-black/50 backdrop-blur-sm"></div>
          <div className="relative bg-white dark:bg-gray-800 rounded-2xl shadow-xl max-w-lg w-full max-h-[80vh] overflow-hidden flex flex-col" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-start justify-between p-6 border-b dark:border-gray-700">
              <div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Kegiatan</h3>
                <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                  {new Intl.DateTimeFormat('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(selectedDate)}
                </p>
              </div>
              <button
                onClick={() => setShowEventModal(false)}
                className="text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300 transition"
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            
            <div className="flex-1 overflow-y-auto p-6">
              <div className="space-y-3">
                {selectedDateEvents.map((event) => {
                  const isExpanded = expandedEventId === event.id;
                  return (
                    <div key={event.id} className="border border-gray-200 dark:border-gray-700 rounded-xl overflow-hidden bg-white dark:bg-gray-700/50 shadow-sm">
                      {/* Accordion Header */}
                      <button
                        onClick={() => toggleEventDetail(event.id)}
                        className="w-full p-4 flex items-center justify-between hover:bg-gray-50 dark:hover:bg-gray-700 transition"
                      >
                        <div className="flex items-start gap-3 flex-1 text-left">
                          <div className="flex-shrink-0 mt-1">
                            <div className={`h-10 w-10 rounded-lg flex items-center justify-center ${
                              event.isNationalHoliday ? 'bg-rose-100 dark:bg-rose-900/30' : 'bg-teal-100 dark:bg-teal-900/30'
                            }`}>
                              <svg xmlns="http://www.w3.org/2000/svg" className={`h-5 w-5 ${
                                event.isNationalHoliday ? 'text-rose-600 dark:text-rose-400' : 'text-teal-600 dark:text-teal-400'
                              }`} viewBox="0 0 20 20" fill="currentColor">
                                <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" />
                              </svg>
                            </div>
                          </div>
                          <div className="flex-1 min-w-0">
                            <h4 className="font-semibold text-gray-900 dark:text-white">{event.title}</h4>
                            {event.isNationalHoliday && (
                              <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-rose-100 dark:bg-rose-900/30 text-rose-800 dark:text-rose-300 mt-1">
                                Hari Libur Nasional
                              </span>
                            )}
                          </div>
                        </div>
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className={`h-5 w-5 text-gray-400 transition-transform duration-200 flex-shrink-0 ml-2 ${
                            isExpanded ? 'rotate-180' : ''
                          }`}
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                        >
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>

                      {/* Accordion Content */}
                      {isExpanded && (
                        <div className="px-4 pb-4 border-t border-gray-100 dark:border-gray-600 bg-gray-50 dark:bg-gray-800/50">
                          <div className="pt-4 space-y-3">
                            {/* Description */}
                            {event.description && event.description !== event.title && (
                              <div>
                                <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">Deskripsi</p>
                                <p className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-line">{event.description}</p>
                              </div>
                            )}

                            {/* Location */}
                            {event.location && (
                              <div>
                                <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">Lokasi</p>
                                <div className="flex items-start gap-2">
                                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-gray-400 dark:text-gray-500 mt-0.5" viewBox="0 0 20 20" fill="currentColor">
                                    <path fillRule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
                                  </svg>
                                  <p className="text-sm text-gray-700 dark:text-gray-300">{event.location}</p>
                                </div>
                              </div>
                            )}

                            {/* Creator */}
                            {event.creator && (
                              <div>
                                <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">Dibuat oleh</p>
                                <p className="text-sm text-gray-700 dark:text-gray-300">{event.creator}</p>
                              </div>
                            )}

                            {/* Date Range */}
                            {event.start && event.end && event.start !== event.end && (
                              <div>
                                <p className="text-xs font-medium text-gray-500 dark:text-gray-400 mb-1">Periode</p>
                                <p className="text-sm text-gray-700 dark:text-gray-300">
                                  {event.start} s/d {event.end}
                                </p>
                              </div>
                            )}

                            {/* Link to Google Calendar */}
                            {event.htmlLink && (
                              <div className="pt-2">
                                <a
                                  href={event.htmlLink}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="inline-flex items-center gap-2 text-sm font-medium text-teal-600 dark:text-teal-400 hover:text-teal-700 dark:hover:text-teal-300"
                                >
                                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                                  </svg>
                                  Lihat di Google Calendar
                                </a>
                              </div>
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default Calendar;

// src/components/Calendar.vue
<template>
  <div class="p-4">
    <div class="flex items-center justify-between mb-3">
      <div class="text-sm font-medium text-gray-900">{{ monthYear }}</div>
      <div class="flex items-center gap-2">
          <button @click="prevMonth" aria-label="Bulan sebelumnya" class="inline-flex items-center justify-center h-8 w-8 rounded bg-white border text-gray-700 hover:shadow hover:bg-gray-50 transition-colors duration-150">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="none" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4l-6 6 6 6" />
            </svg>
          </button>
          <button @click="goToToday" class="px-2 py-1 rounded bg-teal-600 text-white text-sm hover:brightness-95">Hari ini</button>
          <button @click="nextMonth" aria-label="Bulan berikutnya" class="inline-flex items-center justify-center h-8 w-8 rounded bg-white border text-gray-700 hover:shadow hover:bg-gray-50 transition-colors duration-150">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="none" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 4l6 6-6 6" />
            </svg>
          </button>
          <button @click="refresh" title="Segarkan" class="ml-2 inline-flex items-center gap-2 px-2 py-1 rounded bg-white border text-sm hover:shadow group transition-colors duration-150 hover:bg-gray-50 active:scale-95">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 transform transition-transform duration-200 ease-in-out group-hover:rotate-90" viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 11-9-9m0 0v4m0-4h4"/>
            </svg>
          </button>
        </div>
    </div>

    <div class="mb-2 flex items-center gap-2">
      <div v-if="isLoading" class="text-xs text-gray-500 flex items-center gap-2">
        <svg class="animate-spin h-4 w-4 text-gray-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"></path>
        </svg>
        <span>Memuat jadwal...</span>
      </div>
      <div v-else-if="fetchError" class="text-xs text-rose-600">Gagal memuat jadwal</div>
    </div>

    <div class="grid grid-cols-7 gap-1 text-center text-xs text-gray-500">
      <div v-for="d in weekdays" :key="d" class="py-1">{{ d }}</div>
    </div>

    <div class="grid grid-cols-7 gap-1 mt-2">
      <div
        v-for="cell in cells"
        :key="cell.key"
        @click="selectDate(cell.date)"
        @pointerdown="onCellPointerDown($event, cell)"
        @mouseenter="onCellEnter(cell, $event)"
        @mousemove="onCellMove($event)"
        @mouseleave="onCellLeave"
        :class="[
          'p-2 border rounded-md overflow-hidden bg-white cursor-pointer flex flex-col',
          'calendar-cell',
          !cell.isCurrentMonth ? 'bg-gray-50 text-gray-400' : 'text-gray-700 hover:shadow-sm'
        ]"
      >
          <div class="flex-none h-10 flex items-center justify-center">
            <div :class="[ isHoliday(cell.date) ? 'text-rose-700' : (isToday(cell.date) ? 'text-teal-700' : 'text-gray-700') ]" class="text-center">
              <span class="inline-flex items-center justify-center w-8 h-8 leading-none text-base align-middle" :class="badgeClassForDate(cell.date)">
                {{ cell.date.getDate() }}
              </span>
            </div>
          </div>

          <div v-if="eventsFor(cell.date).length" class="w-full mt-2 cell-events">
            <ul class="space-y-1 text-left text-[11px]">
              <li v-for="(ev, i) in eventsFor(cell.date).slice(0,2)" :key="i" :class="['truncate px-1 rounded text-white', ev.isHoliday ? 'bg-rose-600/90' : 'bg-teal-600/90']">{{ ev.title }}</li>
              <li v-if="eventsFor(cell.date).length>2" class="text-[11px] text-gray-500">+{{ eventsFor(cell.date).length - 2 }} lainnya</li>
            </ul>
          </div>
      </div>
    </div>

    <!-- Tooltip -->
    <teleport to="body">
      <div
        v-show="tooltipVisible"
        class="calendar-tooltip fixed z-50 pointer-events-none max-w-xs w-auto"
        :style="{ left: tooltipX + 'px', top: tooltipY + 'px' }"
        role="tooltip"
      >
        <div class="tooltip-inner bg-white border rounded-lg shadow-lg p-2 text-xs text-gray-800 relative">
          <div v-html="tooltipContent"></div>
        </div>
      </div>
    </teleport>

    <!-- Modal: event details -->
    <div v-if="showModal" class="fixed inset-0 z-50 flex items-center justify-center">
      <div class="absolute inset-0 bg-black/50" @click="closeModal"></div>
      <div class="relative z-10 w-full max-w-md bg-white rounded-lg shadow-lg overflow-hidden">
        <div class="flex items-center justify-between px-4 py-3 border-b">
          <div>
            <div class="text-sm font-medium text-gray-900">Kegiatan - {{ selectedDateLabel }}</div>
            <div class="text-xs text-gray-500">{{ selectedDateHuman }}</div>
          </div>
          <button @click="closeModal" class="text-gray-500 hover:text-gray-700">✕</button>
        </div>
        <div class="p-4">
          <ul v-if="selectedEvents.length" class="space-y-3">
            <li v-for="(ev, i) in selectedEvents" :key="i" class="p-3 rounded-lg border">
                  <div class="font-medium text-gray-900">{{ ev.title }}</div>
                  <div class="mt-1 text-xs text-gray-500">
                    <span v-if="ev.startTime">{{ ev.startTime }}</span>
                    <span v-if="ev.startTime && ev.endTime"> - </span>
                    <span v-if="ev.endTime">{{ ev.endTime }}</span>
                    <span v-if="ev.timeZone" class="ml-2 font-medium">{{ ev.timeZone }}</span>
                  </div>
                  <div v-if="ev.desc" class="mt-2 text-sm text-gray-600" v-html="ev.desc"></div>
            </li>
          </ul>
          <div v-else class="text-sm text-gray-500">Tidak ada kegiatan pada tanggal ini.</div>
        </div>
        <div class="px-4 py-3 border-t text-right">
          <button @click="closeModal" class="px-3 py-1 rounded bg-teal-600 text-white">Tutup</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch, onUnmounted, nextTick } from 'vue';
import axios from 'axios';

const today = new Date();
const viewDate = ref(new Date(today.getFullYear(), today.getMonth(), 1));

const weekdays = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];

function formatKey(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${dd}`;
}

// Events fetched from backend
const eventsRef = ref([]);
const isLoading = ref(false);
const fetchError = ref(null);

// Simple per-month cache in localStorage to reduce requests
const CACHE_TTL_MS = 1000 * 60 * 5; // 5 minutes
function cacheKeyFor(y, m) { return `calendar_events_${y}_${m}`; }
function loadCache(y, m) {
  try {
    const raw = localStorage.getItem(cacheKeyFor(y,m));
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (!parsed || !parsed.ts || !parsed.items) return null;
    if (Date.now() - parsed.ts > CACHE_TTL_MS) return null;
    return parsed.items;
  } catch (e) { return null; }
}
function saveCache(y, m, items) {
  try { localStorage.setItem(cacheKeyFor(y,m), JSON.stringify({ ts: Date.now(), items })); } catch(e){}
}

// Holiday cache (daily)
const holidayDatesRef = ref(new Set());
const HOLIDAY_CACHE_TTL_MS = 1000 * 60 * 60 * 24; // 24 hours
function holidayCacheKeyFor(y, m) { return `holiday_dates_${y}_${m}`; }
function loadHolidayCache(y, m) {
  try {
    const raw = localStorage.getItem(holidayCacheKeyFor(y,m));
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (!parsed || !parsed.ts || !parsed.items) return null;
    if (Date.now() - parsed.ts > HOLIDAY_CACHE_TTL_MS) return null;
    return parsed.items;
  } catch (e) { return null; }
}
function saveHolidayCache(y, m, items) {
  try { localStorage.setItem(holidayCacheKeyFor(y,m), JSON.stringify({ ts: Date.now(), items })); } catch(e){}
}

async function fetchHolidaysForView(force = false) {
  try {
    const y = viewDate.value.getFullYear();
    const m = viewDate.value.getMonth() + 1;
    if (!force) {
      const cached = loadHolidayCache(y, m);
      if (cached) {
        holidayDatesRef.value = new Set(cached.map(d => String(d)));
        return;
      }
    }

    const url = `/dayoffapi?month=${m}&year=${y}`;
    const resp = await axios.get(url);
    const data = resp && resp.data ? resp.data : null;

    let items = [];
    if (Array.isArray(data)) items = data;
    else if (data && Array.isArray(data.data)) items = data.data;
    else if (data && Array.isArray(data.items)) items = data.items;
    else if (data && typeof data === 'object') {
      // maybe object with date keys
      const keys = Object.keys(data || {});
      keys.forEach(k => {
        if (/^\d{4}-\d{2}-\d{2}$/.test(k) && data[k]) items.push({ date: k });
      });
    }

    const parsedDates = [];
    items.forEach(it => {
      const ds = it.date || it.tanggal || it.day || it.day_string || it.dayDate || it.day_date || it.dayName || null;
      if (ds) {
        try {
          const d = new Date(ds);
          if (!isNaN(d)) parsedDates.push(formatKey(d));
        } catch (e) {}
      } else if (typeof it === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(it)) {
        parsedDates.push(it);
      }
    });

    // Fallback: also mark Sundays by scanning the month
    // (we still store only dates returned by API; Sundays are handled in isHoliday)

    holidayDatesRef.value = new Set(parsedDates);
    try { saveHolidayCache(y, m, parsedDates); } catch(e){}
  } catch (err) {
    console.warn('Failed to fetch holiday data', err);
  }
}

// Normalize server events into { id?, date: 'YYYY-MM-DD', title, time?, desc?, isHoliday }
function normalizeServerEvent(e) {
  let dateStr = null;
  // Many event shapes: e.date, e.start (string), e.start.date, e.start.dateTime
  if (e.date) dateStr = e.date;
  else if (e.start) {
    if (typeof e.start === 'string') {
      try { dateStr = formatKey(new Date(e.start)); } catch (err) { dateStr = null; }
    } else if (e.start.date) {
      dateStr = String(e.start.date);
    } else if (e.start.dateTime) {
      try { dateStr = formatKey(new Date(e.start.dateTime)); } catch (err) { dateStr = null; }
    }
  } else if (e.startDate) dateStr = e.startDate;

  const title = e.summary || e.title || e.name || 'Tanpa judul';
  let time = e.time || null;
  if (!time && e.start) {
    try {
      const dt = (typeof e.start === 'string') ? new Date(e.start) : (e.start && e.start.dateTime ? new Date(e.start.dateTime) : null);
      if (dt && !isNaN(dt)) time = dt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    } catch (err) { time = null; }
  }

  // Detect holiday by server flag, organizer/creator email, or keywords in title/summary
  const titleLower = String(title).toLowerCase();
  const holidayKeywords = /\blibur\b|hari libur|\bcuti\b|nasional|national|idul|lebaran|nyepi|tahun baru|kemerdekaan|hari raya|liburan/i;
  const creatorEmail = (e.creator && e.creator.email) ? String(e.creator.email).toLowerCase() : '';
  const organizerEmail = (e.organizer && e.organizer.email) ? String(e.organizer.email).toLowerCase() : '';
  const isHoliday = (e.holiday === true) || (e.type === 'holiday') || holidayKeywords.test(titleLower) || /holiday|libur/.test(creatorEmail) || /holiday|libur/.test(organizerEmail);

  // parse start/end times (if present) and timezone label
  const startObj = e.start || {};
  const endObj = e.end || {};
  let startTimeStr = null;
  let endTimeStr = null;
  let tzLabel = null;
  try {
    if (startObj.dateTime) {
      const sd = new Date(startObj.dateTime);
      if (!isNaN(sd)) startTimeStr = sd.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      // derive tz label from offset if not provided
      if (startObj.timeZone) tzLabel = startObj.timeZone;
      else if (!tzLabel && sd && !isNaN(sd)) tzLabel = mapOffsetToIndoLabel(-sd.getTimezoneOffset() / 60);
    } else if (startObj.date) {
      startTimeStr = null; // all-day
      if (startObj.timeZone) tzLabel = startObj.timeZone;
    }
    if (endObj.dateTime) {
      const ed = new Date(endObj.dateTime);
      if (!isNaN(ed)) endTimeStr = ed.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      if (!tzLabel) {
        if (endObj.timeZone) tzLabel = endObj.timeZone;
        else if (ed && !isNaN(ed)) tzLabel = mapOffsetToIndoLabel(-ed.getTimezoneOffset() / 60);
      }
    } else if (endObj.date) {
      // all-day
      endTimeStr = null;
      if (!tzLabel && endObj.timeZone) tzLabel = endObj.timeZone;
    }
  } catch (err) {
    // ignore
  }

  // normalize tzLabel to short form if possible (WIB/WITA/WIT) or keep original
  const shortTz = mapToShortIndoTz(tzLabel);

  return { id: e.id, date: dateStr, title, time: time || startTimeStr, startTime: startTimeStr, endTime: endTimeStr, timeZone: shortTz, desc: e.description || e.desc || '', isHoliday };
}

function mapOffsetToIndoLabel(offset) {
  // offset in hours (e.g., 7, 8, 9)
  if (offset === 7) return 'WIB';
  if (offset === 8) return 'WITA';
  if (offset === 9) return 'WIT';
  if (typeof offset === 'number' && !isNaN(offset)) return `UTC${offset >= 0 ? '+' + offset : offset}`;
  return null;
}

function mapToShortIndoTz(tz) {
  if (!tz) return '';
  const s = String(tz).toLowerCase();
  if (s.includes('jakarta') || s.includes('wib') || s.includes('asia/jakarta')) return 'WIB';
  if (s.includes('makassar') || s.includes('wita') || s.includes('asia/makassar') || s.includes('asia/denpasar')) return 'WITA';
  if (s.includes('jayapura') || s.includes('wit') || s.includes('asia/jayapura')) return 'WIT';
  // if tz looks like UTC±, return as-is
  if (/utc|gmt|\+\d|\-\d/.test(s)) return tz;
  return tz;
}

function isHoliday(d) {
  // Sunday is holiday
  if (d.getDay() === 0) return true;
  const key = formatKey(d);
  if (holidayDatesRef.value && holidayDatesRef.value.has(key)) return true;
  return eventsFor(d).some(ev => ev.isHoliday);
}

function badgeClassForDate(d) {
  if (isHoliday(d)) return 'ring-2 ring-rose-200 rounded-full bg-rose-50';
  if (isToday(d)) return 'ring-2 ring-teal-200 rounded-full bg-teal-50';
  return '';
}

const eventsByDate = computed(() => {
  const map = {};
  eventsRef.value.forEach(ev => {
    if (!ev.date) return;
    if (!map[ev.date]) map[ev.date] = [];
    map[ev.date].push(ev);
  });
  return map;
});

function eventsFor(d) {
  return eventsByDate.value[formatKey(d)] || [];
}

const monthYear = computed(() => {
  return new Intl.DateTimeFormat('id-ID', { month: 'long', year: 'numeric' }).format(viewDate.value);
});

function startGridDate(vd) {
  const first = new Date(vd.getFullYear(), vd.getMonth(), 1);
  const dow = first.getDay(); // 0..6
  const start = new Date(first);
  start.setDate(first.getDate() - dow);
  return start;
}

const cells = computed(() => {
  const start = startGridDate(viewDate.value);
  const out = [];
  for (let i = 0; i < 42; i++) {
    const d = new Date(start);
    d.setDate(start.getDate() + i);
    out.push({ key: formatKey(d), date: d, isCurrentMonth: d.getMonth() === viewDate.value.getMonth() });
  }
  return out;
});

function isToday(d) {
  return formatKey(d) === formatKey(today);
}

function prevMonth() {
  viewDate.value = new Date(viewDate.value.getFullYear(), viewDate.value.getMonth() - 1, 1);
}

function nextMonth() {
  viewDate.value = new Date(viewDate.value.getFullYear(), viewDate.value.getMonth() + 1, 1);
}

function goToToday() {
  viewDate.value = new Date(today.getFullYear(), today.getMonth(), 1);
}

// Fetch events from backend endpoint `/cmb/calendar` for the current view month
// Implementation is provided in the enhanced `fetchEventsForView(force = false)` below.
async function fetchEventsForView(force = false) {
  isLoading.value = true;
  fetchError.value = null;
  try {
    const y = viewDate.value.getFullYear();
    const m = viewDate.value.getMonth() + 1; // 1-based month for API

    // Use cache when available (unless force)
    if (!force) {
      const cached = loadCache(y, m);
      if (cached) {
        eventsRef.value = cached.map(normalizeServerEvent).filter(e => !!e.date);
        isLoading.value = false;
        return;
      }
    }

    const token = localStorage.getItem('token') || '';
    const apiToken = import.meta.env.VITE_SSO_GENERATE_TOKEN || '';

    const url = `/cmb/auto-calendar/fetch?period=${y}-${m}`;
    const headers = {
      'X-Api-Token': apiToken,
    };
    if (token) headers['Authorization'] = `Bearer ${token}`;

    const resp = await axios.get(url, { headers });
    const data = resp && resp.data ? resp.data : [];

    // If backend tells us Google token is missing for the user, ask and redirect to Google connect
    if (data && typeof data === 'object' && data.error && String(data.error).toLowerCase().includes('google token not found')) {
      try {
        const proceed = (typeof Swal !== 'undefined')
          ? await Swal.fire({ title: 'Akun Google belum terhubung', text: 'Anda akan diarahkan untuk menghubungkan akun Google.', icon: 'warning', showCancelButton: true, confirmButtonText: 'Buka koneksi', cancelButtonText: 'Batal' }).then(r=>r.isConfirmed)
          : confirm('Akun Google belum terhubung. Buka halaman koneksi?');
        if (proceed) {
          const base = (import.meta.env.VITE_CMB_BASE || '').replace(/\/$/, '');
          const authUrl = base ? `${base}/auth/google` : '/auth/google';
          window.open(authUrl, '_blank', 'noopener,noreferrer');
        }
      } catch (e) {
        console.warn('Failed to open Google auth tab', e);
      }
      eventsRef.value = [];
      isLoading.value = false;
      return;
    }

    // Response might be array or wrapped as { events: [...] } or { items: [...] }
    const list = Array.isArray(data)
      ? data
      : (Array.isArray(data.events) ? data.events : (Array.isArray(data.items) ? data.items : []));
    // Save raw list to cache for this month
    try { saveCache(y, m, list); } catch(e){}
    eventsRef.value = list.map(normalizeServerEvent).filter(e => !!e.date);
  } catch (err) {
    console.error('Failed to fetch calendar events', err);
    fetchError.value = err;
    eventsRef.value = [];
  } finally {
    isLoading.value = false;
  }
}
function refresh() {
  fetchHolidaysForView(true);
  fetchEventsForView(true);
}

onMounted(() => {
  fetchHolidaysForView();
  fetchEventsForView();
});

watch(viewDate, () => {
  fetchHolidaysForView();
  fetchEventsForView();
});

// Tooltip state & handlers
const tooltipVisible = ref(false);
const tooltipContent = ref('');
const tooltipX = ref(0);
const tooltipY = ref(0);
const TOOLTIP_OFFSET_X = 12;
const TOOLTIP_OFFSET_Y = 12;

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, function (c) {
    return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c];
  });
}

function buildTooltipContentFor(date) {
  const human = new Intl.DateTimeFormat('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(date);
  const evs = eventsFor(date);
  let html = `<div class="font-medium mb-1">${escapeHtml(human)}</div>`;
  if (evs && evs.length) {
    html += '<ul class="space-y-1">';
    evs.slice(0, 3).forEach(ev => {
      const timeText = ev.startTime ? `${escapeHtml(ev.startTime)}${ev.endTime ? (' - ' + escapeHtml(ev.endTime)) : ''}` : '';
      const tzText = ev.timeZone ? `${escapeHtml(ev.timeZone)}` : '';
      const badge = ev.isHoliday ? '<span class="text-rose-600">●</span> ' : '';
      html += `<li class="pb-1">
        <div class="font-medium">${badge} ${escapeHtml(ev.title)}</div>
        <div class="text-gray-500 text-[11px] mt-0.5">${timeText ? escapeHtml(timeText) : ''}${timeText && tzText ? ' ' : ''}${tzText ? '(' + escapeHtml(tzText) + ')' : ''}</div>
      </li>`;
    });
    if (evs.length > 3) html += `<li class="text-gray-500">+${evs.length - 3} lainnya</li>`;
    html += '</ul>';
  } else {
    html += '<div class="text-gray-500">Tidak ada kegiatan</div>';
  }
  return html;
}

function onCellEnter(cell, evt) {
  tooltipContent.value = buildTooltipContentFor(cell.date);
  tooltipVisible.value = true;
  onCellMove(evt);
}

function onCellMove(evt) {
  if (!evt || typeof window === 'undefined') return;
  const x = evt.clientX + TOOLTIP_OFFSET_X;
  const y = evt.clientY + TOOLTIP_OFFSET_Y;
  const approxWidth = 260;
  const approxHeight = 120;
  const maxX = Math.max(8, window.innerWidth - approxWidth - 8);
  const maxY = Math.max(8, window.innerHeight - approxHeight - 8);
  tooltipX.value = Math.min(x, maxX);
  tooltipY.value = Math.min(y, maxY);
}

function onCellLeave() {
  tooltipVisible.value = false;
}

// Touch / pointer support: show tooltip on touch and auto-hide
const hideTimeout = ref(null);
function clearHideTimeout() {
  if (hideTimeout.value) {
    clearTimeout(hideTimeout.value);
    hideTimeout.value = null;
  }
}

function onCellPointerDown(evt, cell) {
  try {
    const pType = evt && evt.pointerType ? evt.pointerType : (evt.type === 'touchstart' ? 'touch' : 'mouse');
    if (pType !== 'touch') return;
    // prevent the subsequent click/select on touch — treat as tap-to-show
    if (evt.cancelable) evt.preventDefault();
    if (evt.stopPropagation) evt.stopPropagation();

    tooltipContent.value = buildTooltipContentFor(cell.date);
    tooltipVisible.value = true;
    onCellMove(evt);

    clearHideTimeout();
    hideTimeout.value = setTimeout(() => {
      tooltipVisible.value = false;
      hideTimeout.value = null;
    }, 4000);
  } catch (e) {
    // ignore
  }
}

onUnmounted(() => {
  clearHideTimeout();
});

// --- Per-row event height syncing (Option B) ---
function debounce(fn, wait = 120) {
  let t = null;
  return (...args) => {
    if (t) clearTimeout(t);
    t = setTimeout(() => { fn(...args); t = null; }, wait);
  };
}

function syncRowEventHeights() {
  nextTick(() => {
    const cells = Array.from(document.querySelectorAll('.calendar-cell'));
    if (!cells.length) return;
    const cols = 7;
    const rows = Math.ceil(cells.length / cols);
    for (let r = 0; r < rows; r++) {
      const rowCells = cells.slice(r * cols, r * cols + cols);
      let maxH = 0;
      rowCells.forEach(c => {
        const ev = c.querySelector('.cell-events');
        if (!ev) return;
        // reset to auto so we measure natural content height
        ev.style.height = 'auto';
        const h = ev.offsetHeight;
        if (h > maxH) maxH = h;
      });
      // apply measured height to all in the row (or clear if zero)
      rowCells.forEach(c => {
        const ev = c.querySelector('.cell-events');
        if (!ev) return;
        ev.style.height = maxH ? (maxH + 'px') : '';
      });
    }
  });
}

const debouncedSync = debounce(syncRowEventHeights, 100);

onMounted(() => {
  window.addEventListener('resize', debouncedSync);
  // initial sync (in case events already loaded)
  debouncedSync();
});

onUnmounted(() => {
  window.removeEventListener('resize', debouncedSync);
});

// Re-sync whenever events change or viewDate changes
watch(eventsRef, () => debouncedSync());
watch(viewDate, () => debouncedSync());

// Modal / selection state
const showModal = ref(false);
const selectedDate = ref(null);

const selectedEvents = computed(() => {
  if (!selectedDate.value) return [];
  return eventsFor(selectedDate.value);
});

const selectedDateLabel = computed(() => {
  return selectedDate.value ? formatKey(selectedDate.value) : '';
});

const selectedDateHuman = computed(() => {
  return selectedDate.value
    ? new Intl.DateTimeFormat('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(selectedDate.value)
    : '';
});

function selectDate(d) {
  selectedDate.value = new Date(d.getFullYear(), d.getMonth(), d.getDate());
  showModal.value = true;
}

function closeModal() {
  showModal.value = false;
  selectedDate.value = null;
}
</script>

<style scoped>
/* small tweaks */
.truncate { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

/* Tooltip styles */
.calendar-tooltip { transform-origin: top left; }
.calendar-tooltip .tooltip-inner::after {
  content: "";
  position: absolute;
  width: 12px;
  height: 12px;
  background: white;
  left: 12px;
  top: -6px;
  transform: rotate(45deg);
  border-left: 1px solid rgba(0,0,0,0.08);
  border-top: 1px solid rgba(0,0,0,0.08);
  box-shadow: -2px -2px 6px rgba(0,0,0,0.03);
}

@media (max-width: 640px) {
  .calendar-tooltip { max-width: 85vw; }
}
</style>
